version: "3"
services:
  varnish:
    image: "varnish:test"
    ports:
      - 3000:3000
    environment:
      VARNISH_HTTP_PORT: "3000"
      VARNISH_PROXY_PORT: "5000"
    depends_on:
      - icx
  icx:
    depends_on:
      - redis
    image: "icx:test"
    command:
      - cargo
      - run
      - --
      - --debug
      - -v
      - --log
      - "stderr"
      - --replica
      - "https://ic0.app"
      - --address
      - 0.0.0.0:5000
      - --redis-url
      - "redis://redis:6379"
      - --phonebook-id
      - "ngrpb-5qaaa-aaaaj-adz7a-cai"
  redis:
    image: redis:alpine