variable "health_check_path" {}
variable "tsl_certificate_arn" {}
variable "load_balancer_type" {}
variable "container_port" {}
variable "nlb_name" {}
variable "nlb_tg_name" {}
variable "public_subnet_ids" {}
variable "vpc_id" {}
variable "waf_enable" {}
variable "waf_web_acl_name" {}
variable "tags" {}