name: 'ICX-PROXY - CI'
on: 
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{steps.image_push.outputs.image_id}}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Checkout NFT Repo
      uses: actions/checkout@v3
      with:
        repository: ORIGYN-SA/origyn_nft
        token: ${{ secrets.GH_PAT }}
        path: origyn_nft
    
    - name: Checkout Phonebook Repo
      uses: actions/checkout@v3
      with:
        repository: ORIGYN-SA/phone_book
        token: ${{ secrets.GH_PAT }}
        path: phone_book

    - name: Docker Compose Action
      uses: isbang/compose-action@v1.3.2
      with:
        compose-file: "./icx-proxy/.ci/docker-compose.yml"
      
    - name: Push Docker Image to Container Registry
      id: image_push
      run: |
        echo "::set-output image_id=https://ghcr.io"

  deploy-docker:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Launch Docker


